[package]
name = "in-cloud"
version = "0.1.0"
authors = ["clpi <clp@clp.is>"]
edition = "2018"

[lib]
name = "in_cloud"
path = "./src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
in-data = { path = "../in-data" }
